apiVersion: v1
kind: Namespace
metadata:
 name: outline
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: outline
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: xxx.xxx.xxx.xxx #Replace with nfs-server ClusterIP
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: outline-pvc
  namespace: outline
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
