apiVersion: v1
kind: PersistentVolume
metadata:
  name: outline-pv
  namespace: apps
  labels:
    name: outline-data
    type: longhorn
spec:
  capacity:
    storage: 10G
  volumeMode: Filesystem
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  csi:
    driver: io.rancher.longhorn
    fsType: ext4
    volumeAttributes:
      numberOfReplicates: '2'
      staleReplicaTimeout: '20'
    volumeHandle: outline-data
