apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-pv-claim
  labels:
    type: longhorn
    app: example
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
